### ISSUE TITLE
Multiple errors during the weekend

### ISSUE THREAD

**Issue by assafza** [kugelblitz-one/Fredo-Public#447]
Please look at your inbox:  jerry_fredo@djint.net
You should have recieved the emails.
Usually I do not get a lot of these but since last week I am getting a lot of those.

I want to check the reason if there is a common ground for all the erros.

**Comment by JerryVDP** [comment]
`Error on number 972547101100. message: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.`
Seems like a user typed an invalid email in EmailResponder, which the email validation function didn't catch, the email validation function only check to see if the string contains "@", we can improve the validation function in the future.


`Error on number 972527738188. message: [HTTP 400] Unable to create record: Invalid media URL(s)`
Fredo tried to send a media item but Twilio refused to accept it for some reason, we don't store media URLs in logs due to privacy concerns, so we can't directly reproduce it.
